backend:
  name: github
  repo: claudiomateluna/nuevoBuenaCaza

media_folder: 'img/uploads'

collections:
  - name: 'configuracion-basica'
    label: 'Configuración Básica'
    files:
      - label: 'Configuración Básica'
        name: 'buenacaza'
        file: '_data/buenacaza.yml'
        fields:
          - label: 'Titulo'
            name: 'titulo'
            widget: 'string'
            hint: 'Titulo del Sitio Web'
          - label: 'Nombre'
            name: 'name'
            widget: 'string'
            hint: 'Nombre del sitio web'
          - label: 'Correo Electrónico'
            name: 'email'
            widget: 'string'
            hint: 'Correo Electrónico del sitio web'
          - label: 'Resumen'
            name: 'resumen'
            widget: 'string'
            hint: 'Descripción del sitio web (esto es utilizado para SEO del sitio)'
          - label: 'Redes Sociales'
            name: 'redes_sociales'
            widget: 'object'
            fields: 
              - label: 'Twitter'
                name: 'twitter'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Facebook'
                name: 'facebook'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Instagram'
                name: 'instagram'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
  - name: 'biografias'
    label: 'Biografías'
    description: 'Edición e incorporación de biografías en el sitio'
    folder: '_biografias'
    create: true
    fields: 
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'articulos'
      - name: 'titulo'
        label: 'Titulo'
        widget: 'string'
      - name: 'img'
        label: 'Imagen del Articulo'
        widget: 'image'
        hint: 'Imagen principal del articulo la misma que se muestra al lado derecho en la parte superior del mismo.'
      - name: 'categoria'
        label: 'Categoria'
        widget: 'list'
        hint: 'Incorpore categorias que se asocien a esta biografía'
      - name: 'pais'
        label: 'Pais'
        widget: 'string'
        hint: 'Indique el país de nacimiento de este personaje'
      - name: 'lugar'
        label: 'Lugar'
        widget: 'string'
        hint: 'Indique el lugar o ciudad de nacimiento de este personaje'
      - name: 'nacimiento'
        label: 'Nacimiento'
        widget: 'date'
        hint: 'indique la fecha de nacimiento del personaje'
      - name: 'defuncion'
        label: 'Defunción'
        widget: 'date'
        hint: 'indique la fecha de defunción del personaje'
      - name: 'ref_nombre'
        label: 'Nombre de la Referencia'
        widget: 'string'
        hint: 'indique el nombre del sitio donde obtuvo esta biografía'
      - name: 'ref_url'
        label: 'URL de la Referencia'
        widget: 'string'
        hint: 'indique la URL del sitio donde obtuvo la biografía'
      - name: 'resumen'
        label: 'Resumen'
        widget: 'string'
        hint: 'Un breve resumen con menos de 140 caracteres sobre lo que trata esta Publicación'
      - name: 'orden'
        label: 'Orden'
        widget: 'number'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
